### ISSUE TITLE
Rails code base

### ISSUE THREAD

**Issue by axelson** [CfABrigadePhiladelphia/CyclePhilly-iOS-app#5]
Is the rails code base available? I'm having trouble finding the link to it.

I'd like to stand this up in Honolulu if possible.

**Comment by flibbertigibbet** [comment]
@emelleme?

**Comment by flibbertigibbet** [comment]
You can find it over at https://github.com/CfABrigadePhiladelphia/cyclephilly now.

Thanks for your interest!
