### ISSUE TITLE
add Indego station map overlay

### ISSUE THREAD

**Issue by flibbertigibbet** [CfABrigadePhiladelphia/CyclePhilly-iOS-app#7]
* Add overlay to the map view with the Indego bike rental stations
* Give the markers popups with information on station name, status (if not active) and bikes/docks available (if active)
* Allow overlay to be switched on/off
* Use Indego image resources in markers
* Color markers by status to match colors used by Indego website station map

**Comment by LabLayers** [comment]
:+1:
